import type { PracticeThemeId, Scenario } from "@/lib/types";
import { ADDITIONAL_SCENARIOS } from "./additionalScenarios";
import { PRACTICE_THEMES } from "./themes";

// Practice themes (history, poems, medical, …) double as scenario categories,
// so their labels live in one place.
const THEME_LABELS = Object.fromEntries(
  PRACTICE_THEMES.map((theme) => [theme.id, theme.categoryLabel]),
) as Record<PracticeThemeId, string>;

const CATEGORY_LABELS: Record<Scenario["category"], string> = {
  website: "Website Development",
  "google-ads": "Google Ads",
  tracking: "Tracking & Analytics",
  "meta-ads": "Meta Ads",
  "tiktok-ads": "TikTok Ads",
  reporting: "Reporting",
  history: THEME_LABELS.history,
  quotes: THEME_LABELS.quotes,
  ielts: THEME_LABELS.ielts,
  vocabulary: THEME_LABELS.vocabulary,
  poems: THEME_LABELS.poems,
  medical: THEME_LABELS.medical,
};

export const SCENARIOS: Scenario[] = [
  {
    id: "WEB-01",
    version: 1,
    category: "website",
    categoryLabel: CATEGORY_LABELS.website,
    title: "Discovery: an unclear brief",
    situation: "Client wants a business website but has an unclear brief.",
    learnerGoal: "Ask about goals, visitors, pages, and required actions.",
    difficultyDefault: "beginner",
    estimatedMinutes: 8,
    brief:
      "Amina runs a small cleaning business and wants 'a website like everyone else has'. She has not thought about pages, visitors, or goals yet. Help her clarify what she actually needs.",
    persona: {
      name: "Amina Karim",
      role: "Owner",
      business: "Sparkle Home Cleaning",
      traits: ["friendly", "not technical", "a little unsure of what she needs"],
    },
    facts: {
      business: "Local home cleaning service, 3 employees",
      currentWebsite: "None, only a Facebook page",
      budgetHint: "Has not set a budget yet",
    },
    hiddenFacts: {
      mainGoal: "Wants more phone bookings from local customers",
      timeline: "No fixed deadline, but would like something 'soon'",
    },
    openingMessage:
      "I need a website for my cleaning business. Can you tell me how much it will cost?",
    objectives: [
      "Ask what the website should help visitors do",
      "Ask who the typical visitor is",
      "Ask how many pages might be needed",
      "Avoid quoting a price before requirements are clear",
    ],
    vocabulary: [
      { phrase: "scope of work", meaning: "the tasks and deliverables included in a project", meaningBn: "প্রকল্পের কাজের পরিধি" },
      { phrase: "call to action", meaning: "the action you want a visitor to take", meaningBn: "দর্শনার্থীর কাছ থেকে প্রত্যাশিত পদক্ষেপ" },
      { phrase: "target audience", meaning: "the group of people the website is for", meaningBn: "লক্ষ্য দর্শক" },
      { phrase: "estimate", meaning: "an approximate price before final scope", meaningBn: "আনুমানিক মূল্য" },
      { phrase: "booking", meaning: "reserving a service or appointment", meaningBn: "বুকিং" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "I need a website for my cleaning business. Can you tell me how much it will cost?" },
      { speaker: "freelancer", text: "I can prepare an estimate once I understand what you need. What should the website help customers do?" },
      { speaker: "client", text: "I think... just show that we exist? And maybe let people book a cleaning." },
      { speaker: "freelancer", text: "That's helpful. Do you want customers to book and pay online, or just send a message?" },
      { speaker: "client", text: "Book and pay would be great, if that's not too expensive." },
      { speaker: "freelancer", text: "Online booking with payment is very doable. How many service areas or pages do you imagine, like Home, Services, and Contact?" },
      { speaker: "client", text: "Maybe five pages. I don't have photos or text ready yet though." },
      { speaker: "freelancer", text: "No problem, we can plan the content together. Once we confirm the pages and booking flow, I'll send a clear estimate and timeline." },
    ],
    completionGuidance:
      "Objectives are met when the learner asks about visitor goals, desired actions, and page count before offering a price.",
  },
  {
    id: "WEB-02",
    version: 1,
    category: "website",
    categoryLabel: CATEGORY_LABELS.website,
    title: "Scope creep: landing page becomes a dashboard",
    situation: "Client requests a landing page and later adds a dashboard.",
    learnerGoal: "Clarify deliverables and identify additional scope.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 8,
    brief:
      "Farhan hired you for a simple landing page for his tutoring service. Midway through the project he asks for a student dashboard with login. Recognize the new scope and respond professionally.",
    persona: {
      name: "Farhan Chowdhury",
      role: "Founder",
      business: "BrightPath Tutoring",
      traits: ["busy", "assumes small changes are easy"],
    },
    facts: {
      originalScope: "One-page landing site with contact form",
      agreedPrice: "$350 for the landing page",
      agreedTimeline: "1 week",
    },
    hiddenFacts: {
      dashboardComplexity: "A student login dashboard needs authentication, a database, and ongoing maintenance",
      clientBudgetFlex: "Farhan could pay more if he understands why it costs extra",
    },
    openingMessage:
      "This landing page looks great! One more thing — can you also add a dashboard where students log in to see their schedule?",
    objectives: [
      "Acknowledge the request without agreeing to unpaid extra scope",
      "Explain that a login dashboard is a separate, larger feature",
      "Propose a revised scope, price, or timeline",
      "Keep the tone positive and collaborative",
    ],
    vocabulary: [
      { phrase: "scope creep", meaning: "extra work added without adjusting price or time", meaningBn: "কাজের পরিধি অপ্রত্যাশিতভাবে বেড়ে যাওয়া" },
      { phrase: "deliverable", meaning: "a specific item you agree to produce", meaningBn: "প্রদেয় কাজের ফলাফল" },
      { phrase: "change request", meaning: "a formal request to modify the agreed project", meaningBn: "পরিবর্তনের অনুরোধ" },
      { phrase: "authentication", meaning: "verifying who a user is, e.g. login", meaningBn: "প্রমাণীকরণ" },
      { phrase: "revised quote", meaning: "an updated price after scope changes", meaningBn: "সংশোধিত মূল্য" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "This landing page looks great! Can you also add a dashboard where students log in?" },
      { speaker: "freelancer", text: "I'm glad you like it! A login dashboard is a bigger feature than the landing page we agreed on." },
      { speaker: "client", text: "Really? I thought it would just be one more page." },
      { speaker: "freelancer", text: "It needs secure logins and a database to store each student's schedule, so it's a separate project." },
      { speaker: "client", text: "Okay, how much would that add?" },
      { speaker: "freelancer", text: "Let me put together a revised quote and timeline for the dashboard so you can decide." },
    ],
    completionGuidance:
      "Objectives are met when the learner distinguishes the original scope from the new request and proposes a revised plan rather than absorbing the work silently.",
  },
  {
    id: "WEB-03",
    version: 1,
    category: "website",
    categoryLabel: CATEGORY_LABELS.website,
    title: "An unrealistic timeline",
    situation: "Client wants the website finished in three days.",
    learnerGoal: "Ask about dependencies and propose realistic milestones.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief:
      "Rina needs a website for a product launch event. She asks if it can be ready in three days, without yet providing content or images.",
    persona: {
      name: "Rina Das",
      role: "Marketing Lead",
      business: "GreenLeaf Organics",
      traits: ["busy", "under pressure from her own boss"],
    },
    facts: {
      requestedPages: "5 pages: Home, Products, About, Contact, Blog",
      launchEvent: "In 3 days",
      contentStatus: "No text or images provided yet",
    },
    hiddenFacts: {
      flexibleScope: "Rina could accept a smaller 2-page version for launch day",
    },
    openingMessage: "We have a launch event in three days. Can the whole website be ready by then?",
    objectives: [
      "Ask what content and assets are currently available",
      "Explain what depends on receiving content on time",
      "Propose a realistic milestone or a reduced scope for launch day",
      "Avoid promising an unrealistic deadline",
    ],
    vocabulary: [
      { phrase: "milestone", meaning: "a key checkpoint in a project timeline", meaningBn: "মাইলফলক" },
      { phrase: "dependency", meaning: "something that must happen before another task can start", meaningBn: "নির্ভরতা" },
      { phrase: "minimum viable version", meaning: "the smallest useful version of a product", meaningBn: "সর্বনিম্ন কার্যকর সংস্করণ" },
      { phrase: "turnaround time", meaning: "how long a task takes to complete", meaningBn: "সম্পন্ন হতে যে সময় লাগে" },
      { phrase: "realistic deadline", meaning: "a deadline that accounts for real constraints", meaningBn: "বাস্তবসম্মত সময়সীমা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "We have a launch event in three days. Can the whole website be ready by then?" },
      { speaker: "freelancer", text: "Three days is tight for five pages. Do you already have the text and images ready?" },
      { speaker: "client", text: "Not yet, we're still writing the product descriptions." },
      { speaker: "freelancer", text: "That will affect the timeline, since I need the content to build the pages." },
      { speaker: "client", text: "Is there anything we can do to make launch day work?" },
      { speaker: "freelancer", text: "We could launch with a single home page announcing the event, then add the other pages within the following week." },
    ],
    completionGuidance:
      "Objectives are met when the learner ties the timeline to content availability and proposes a workable milestone instead of just saying yes or no.",
  },
  {
    id: "WEB-04",
    version: 1,
    category: "website",
    categoryLabel: CATEGORY_LABELS.website,
    title: "WordPress, Shopify, or custom?",
    situation: "Client asks about WordPress, Shopify, or a custom application.",
    learnerGoal: "Explain tradeoffs in plain English and ask about maintenance.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 8,
    brief:
      "Tanvir is opening an online store and has heard different platform names from friends. Help him choose based on his actual needs, not buzzwords.",
    persona: {
      name: "Tanvir Islam",
      role: "Owner",
      business: "Urban Thread Apparel",
      traits: ["nontechnical", "curious", "price-sensitive"],
    },
    facts: {
      productCount: "About 40 clothing products",
      sellingOnline: "Wants to sell directly and accept payments",
      technicalSkill: "No coding experience, has one part-time assistant",
    },
    hiddenFacts: {
      maintenancePreference: "Wants something he can update himself without hiring a developer every time",
    },
    openingMessage:
      "My friend said I should use Shopify, but another said WordPress. What do you think is best for my store?",
    objectives: [
      "Ask about product count, budget, and who will maintain the site",
      "Explain platform tradeoffs in plain, non-technical language",
      "Avoid overwhelming the client with jargon",
      "Recommend an option based on his stated needs",
    ],
    vocabulary: [
      { phrase: "content management system", meaning: "software that lets you edit a website without coding", meaningBn: "কনটেন্ট ম্যানেজমেন্ট সিস্টেম" },
      { phrase: "hosting", meaning: "the service that keeps a website online", meaningBn: "হোস্টিং" },
      { phrase: "maintenance", meaning: "ongoing updates and fixes after launch", meaningBn: "রক্ষণাবেক্ষণ" },
      { phrase: "plugin", meaning: "an add-on that extends website features", meaningBn: "প্লাগইন" },
      { phrase: "custom application", meaning: "software built specifically for one business", meaningBn: "কাস্টম অ্যাপ্লিকেশন" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "My friend said I should use Shopify, but another said WordPress. What do you think?" },
      { speaker: "freelancer", text: "It depends on your needs. Who will update the products day to day, you or your assistant?" },
      { speaker: "client", text: "Probably my assistant, she isn't very technical either." },
      { speaker: "freelancer", text: "Shopify is built for online stores and is easy for non-technical staff to manage products and orders." },
      { speaker: "client", text: "And WordPress?" },
      { speaker: "freelancer", text: "WordPress is more flexible but usually needs more setup and occasional technical maintenance." },
      { speaker: "client", text: "Shopify sounds simpler for us then." },
      { speaker: "freelancer", text: "I agree, given your team. We can also plan how you'll get support after launch." },
    ],
    completionGuidance:
      "Objectives are met when the learner explains at least two tradeoffs simply and connects the recommendation to maintenance needs.",
  },
  {
    id: "WEB-05",
    version: 1,
    category: "website",
    categoryLabel: CATEGORY_LABELS.website,
    title: "Missing content and feedback",
    situation: "Client has not supplied content or feedback.",
    learnerGoal: "Explain the impact and request a specific next step.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief:
      "Two weeks ago you asked Lubna for page text and photos. The project is now delayed because you're still waiting.",
    persona: {
      name: "Lubna Chowdhury",
      role: "Owner",
      business: "Petal & Stem Florist",
      traits: ["busy", "apologetic but often distracted"],
    },
    facts: {
      requestedAt: "2 weeks ago",
      missingItems: "Page text and product photos",
      projectStatus: "Design is ready, waiting on content",
    },
    hiddenFacts: {
      reasonForDelay: "Lubna has been overwhelmed with holiday orders",
    },
    openingMessage: "Hi, sorry for being quiet. How is the website coming along?",
    objectives: [
      "Explain clearly what is still missing",
      "Explain how the missing items are affecting the timeline",
      "Request one specific, actionable next step with a date",
      "Stay professional and non-blaming",
    ],
    vocabulary: [
      { phrase: "pending", meaning: "waiting to be completed or received", meaningBn: "মুলতুবি" },
      { phrase: "bottleneck", meaning: "something that slows down the whole process", meaningBn: "প্রধান বাধা" },
      { phrase: "placeholder", meaning: "temporary content used until the real content arrives", meaningBn: "অস্থায়ী বিষয়বস্তু" },
      { phrase: "follow-up", meaning: "a message sent to check on progress", meaningBn: "ফলোআপ" },
      { phrase: "due date", meaning: "the date something is expected to be delivered", meaningBn: "নির্ধারিত তারিখ" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Hi, sorry for being quiet. How is the website coming along?" },
      { speaker: "freelancer", text: "The design is ready, but I'm still waiting on the page text and product photos we discussed." },
      { speaker: "client", text: "Oh no, I completely forgot with the holiday orders." },
      { speaker: "freelancer", text: "No problem, but that's why the launch has been paused for two weeks now." },
      { speaker: "client", text: "I understand. What do you need most urgently?" },
      { speaker: "freelancer", text: "Could you send at least the homepage text and five product photos by Friday? That would let me move forward." },
    ],
    completionGuidance:
      "Objectives are met when the learner names the missing items, the impact, and one concrete next step with a timeframe.",
  },
  {
    id: "WEB-06",
    version: 1,
    category: "website",
    categoryLabel: CATEGORY_LABELS.website,
    title: "Handover and launch",
    situation: "Website is ready for review and launch.",
    learnerGoal: "Explain testing, revisions, hosting, and ongoing support.",
    difficultyDefault: "beginner",
    estimatedMinutes: 8,
    brief:
      "The website for Hasan's bakery is ready. Walk him through review, revisions, hosting, and what support looks like after launch.",
    persona: {
      name: "Hasan Mahmud",
      role: "Owner",
      business: "Golden Crust Bakery",
      traits: ["excited", "nontechnical", "eager to launch quickly"],
    },
    facts: {
      revisionsIncluded: "2 rounds of revisions included in the price",
      hosting: "Client needs to choose a hosting plan before going live",
      supportPlan: "Optional monthly support package available afterward",
    },
    openingMessage: "It looks amazing! Can we launch it today?",
    objectives: [
      "Explain the review and testing steps before launch",
      "Explain how many revision rounds are included",
      "Explain hosting requirements clearly",
      "Mention ongoing support options without pressuring the client",
    ],
    vocabulary: [
      { phrase: "revision round", meaning: "a set of requested changes reviewed together", meaningBn: "সংশোধনের পর্যায়" },
      { phrase: "go live", meaning: "to make the website publicly available", meaningBn: "লাইভ হওয়া" },
      { phrase: "quality assurance", meaning: "testing to catch problems before launch", meaningBn: "মান নিশ্চিতকরণ" },
      { phrase: "domain", meaning: "the website address, e.g. example.com", meaningBn: "ডোমেইন" },
      { phrase: "support package", meaning: "an ongoing service for fixes and updates", meaningBn: "সহায়তা প্যাকেজ" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "It looks amazing! Can we launch it today?" },
      { speaker: "freelancer", text: "Thank you! Before we launch, let's do a final review together to check every page." },
      { speaker: "client", text: "Sure, what should I look for?" },
      { speaker: "freelancer", text: "Please check the text, photos, and try the contact form. You have two revision rounds included." },
      { speaker: "client", text: "Got it. What about putting it online?" },
      { speaker: "freelancer", text: "We'll need your hosting plan set up first, then I can publish it and confirm everything works." },
      { speaker: "client", text: "And after launch, if something breaks?" },
      { speaker: "freelancer", text: "I offer an optional monthly support package for fixes and small updates, if that's useful to you." },
    ],
    completionGuidance:
      "Objectives are met when the learner covers review, revisions, hosting, and support without skipping any topic.",
  },
  {
    id: "GADS-01",
    version: 1,
    category: "google-ads",
    categoryLabel: CATEGORY_LABELS["google-ads"],
    title: "First discovery call",
    situation: "First discovery call for a lead generation campaign.",
    learnerGoal: "Ask about audience, budget, offer, and success criteria.",
    difficultyDefault: "beginner",
    estimatedMinutes: 8,
    brief:
      "Nasrin wants to run Google Ads for her law consultation service but hasn't defined her audience or goals yet.",
    persona: {
      name: "Nasrin Haque",
      role: "Principal",
      business: "Haque Legal Consultants",
      traits: ["friendly", "professional", "new to advertising"],
    },
    facts: {
      service: "Legal consultations for small businesses",
      pastAdvertising: "Never run paid ads before",
    },
    hiddenFacts: {
      monthlyBudget: "Around $500 per month to start",
      successDefinition: "Wants at least 10 qualified consultation requests per month",
    },
    openingMessage: "I want to start running Google Ads to get more clients. Where do we begin?",
    objectives: [
      "Ask who the ideal client is",
      "Ask about budget expectations",
      "Ask what offer or service the ads should promote",
      "Ask how success will be measured",
    ],
    vocabulary: [
      { phrase: "lead generation", meaning: "getting potential customers to express interest", meaningBn: "লিড জেনারেশন" },
      { phrase: "target audience", meaning: "the specific group ads are shown to", meaningBn: "লক্ষ্য দর্শক" },
      { phrase: "monthly budget", meaning: "how much is spent on ads each month", meaningBn: "মাসিক বাজেট" },
      { phrase: "offer", meaning: "what is being promoted to attract customers", meaningBn: "অফার" },
      { phrase: "success criteria", meaning: "how a campaign's performance will be judged", meaningBn: "সফলতার মানদণ্ড" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "I want to start running Google Ads to get more clients. Where do we begin?" },
      { speaker: "freelancer", text: "Great, let's start with your ideal client. Who usually needs your consultations most?" },
      { speaker: "client", text: "Mostly small business owners who need contract advice." },
      { speaker: "freelancer", text: "That's useful. Do you have a monthly budget in mind for ads?" },
      { speaker: "client", text: "I was thinking around $500 to start." },
      { speaker: "freelancer", text: "That's a reasonable starting point. What would success look like for you after the first month?" },
      { speaker: "client", text: "Maybe 10 people booking a consultation." },
      { speaker: "freelancer", text: "Perfect, that gives us a clear goal to build the campaign around." },
    ],
    completionGuidance:
      "Objectives are met when the learner has asked about audience, budget, offer, and a measurable success target.",
  },
  {
    id: "GADS-02",
    version: 1,
    category: "google-ads",
    categoryLabel: CATEGORY_LABELS["google-ads"],
    title: "Guaranteed leads or sales?",
    situation: "Client asks for guaranteed leads or sales.",
    learnerGoal: "Set expectations and describe a testing plan.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief:
      "Kamal wants a guarantee of a specific number of sales before starting. Explain why that can't be promised and describe a fair testing approach instead.",
    persona: {
      name: "Kamal Ahsan",
      role: "Owner",
      business: "Ahsan Furniture Mart",
      traits: ["skeptical", "budget-conscious"],
    },
    facts: {
      productType: "Furniture, average order $150",
      pastExperience: "Was disappointed by a previous marketer's unclear results",
    },
    openingMessage: "Before we start, can you guarantee me at least 50 sales this month?",
    objectives: [
      "Explain that guaranteed sales cannot be promised honestly",
      "Explain the factors that affect results",
      "Propose a specific testing period and metrics to track",
      "Remain respectful of the client's past disappointment",
    ],
    vocabulary: [
      { phrase: "guarantee", meaning: "a firm promise of a specific result", meaningBn: "নিশ্চয়তা" },
      { phrase: "testing period", meaning: "a set time to try and measure a strategy", meaningBn: "পরীক্ষামূলক সময়কাল" },
      { phrase: "conversion rate", meaning: "the percentage of visitors who complete a goal", meaningBn: "কনভার্সন রেট" },
      { phrase: "realistic expectations", meaning: "expectations grounded in likely outcomes", meaningBn: "বাস্তবসম্মত প্রত্যাশা" },
      { phrase: "performance data", meaning: "measured results used to make decisions", meaningBn: "পারফরম্যান্স ডেটা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Before we start, can you guarantee me at least 50 sales this month?" },
      { speaker: "freelancer", text: "I understand why you want certainty, but no honest advertiser can guarantee exact sales numbers." },
      { speaker: "client", text: "My last marketer promised results and I got nothing." },
      { speaker: "freelancer", text: "That's frustrating, and I want to avoid that here by being transparent from day one." },
      { speaker: "client", text: "So what can you offer instead?" },
      { speaker: "freelancer", text: "Let's run a focused 3-week test, track clicks and leads closely, and review real numbers together." },
    ],
    completionGuidance:
      "Objectives are met when the learner avoids promising guaranteed results and offers a concrete, measurable testing plan.",
  },
  {
    id: "GADS-03",
    version: 1,
    category: "google-ads",
    categoryLabel: CATEGORY_LABELS["google-ads"],
    title: "Worried about expensive clicks",
    situation: "Client worries about expensive clicks.",
    learnerGoal: "Explain costs, lead quality, and planned investigation.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief:
      "Shirin is concerned that her cost-per-click seems high compared to what a friend told her. Explain clearly without guessing at causes you haven't checked.",
    persona: {
      name: "Shirin Akter",
      role: "Owner",
      business: "Akter Dental Clinic",
      traits: ["budget-conscious", "compares notes with friends"],
    },
    facts: {
      currentCpc: "$4.50 average cost per click",
      industry: "Dental services, a competitive and expensive niche",
    },
    hiddenFacts: {
      friendIndustry: "Her friend advertises a much less competitive product",
    },
    openingMessage: "My friend pays $1 per click for her shop, but I'm paying $4.50. Why is mine so expensive?",
    objectives: [
      "Explain that cost per click varies by industry competitiveness",
      "Avoid comparing unlike industries as if they were the same",
      "Propose looking at lead quality, not just click cost",
      "Suggest a specific next step to investigate further",
    ],
    vocabulary: [
      { phrase: "cost per click", meaning: "the price paid each time someone clicks an ad", meaningBn: "প্রতি ক্লিকের খরচ" },
      { phrase: "competitive niche", meaning: "a market where many advertisers compete", meaningBn: "প্রতিযোগিতামূলক বাজার" },
      { phrase: "quality score", meaning: "a metric affecting ad cost and placement", meaningBn: "কোয়ালিটি স্কোর" },
      { phrase: "lead quality", meaning: "how likely a lead is to become a paying customer", meaningBn: "লিডের মান" },
      { phrase: "benchmark", meaning: "a reference point used for comparison", meaningBn: "মানদণ্ড" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "My friend pays $1 per click, but I'm paying $4.50. Why is mine so expensive?" },
      { speaker: "freelancer", text: "Cost per click depends a lot on the industry. Dental services tend to be more competitive than many other businesses." },
      { speaker: "client", text: "So there's nothing wrong with my account?" },
      { speaker: "freelancer", text: "I can't say that without checking, but a higher cost per click alone isn't necessarily a problem." },
      { speaker: "client", text: "What should we look at instead?" },
      { speaker: "freelancer", text: "Let's look at how many of those clicks turn into real appointment requests, since that matters more than the click price alone." },
    ],
    completionGuidance:
      "Objectives are met when the learner explains industry variation honestly and redirects to lead quality and next steps rather than guessing at a diagnosis.",
  },
  {
    id: "GADS-04",
    version: 1,
    category: "google-ads",
    categoryLabel: CATEGORY_LABELS["google-ads"],
    title: "Monthly management proposal",
    situation: "Monthly management proposal.",
    learnerGoal: "Explain account access, responsibilities, fees, and reporting.",
    difficultyDefault: "advanced",
    estimatedMinutes: 8,
    brief:
      "Present a monthly management arrangement to a client who is ready to move forward but needs the details spelled out clearly.",
    persona: {
      name: "Imran Sarker",
      role: "Operations Manager",
      business: "Sarker Home Appliances",
      traits: ["organized", "wants clear written terms"],
    },
    facts: {
      proposedFee: "$400 per month management fee, separate from ad spend",
      reportingSchedule: "Monthly report plus a brief check-in call",
    },
    openingMessage: "We'd like to move forward. What exactly do you need from us, and what do we get each month?",
    objectives: [
      "Explain what account access is needed and why",
      "Clarify who is responsible for what",
      "State the management fee separately from ad spend",
      "Describe the reporting schedule and format",
    ],
    vocabulary: [
      { phrase: "account access", meaning: "permission to view or manage an advertising account", meaningBn: "অ্যাকাউন্ট অ্যাক্সেস" },
      { phrase: "management fee", meaning: "the charge for managing a campaign, separate from ad spend", meaningBn: "ম্যানেজমেন্ট ফি" },
      { phrase: "ad spend", meaning: "money paid to the ad platform for showing ads", meaningBn: "বিজ্ঞাপন খরচ" },
      { phrase: "check-in call", meaning: "a short recurring call to review progress", meaningBn: "পর্যালোচনা কল" },
      { phrase: "responsibilities", meaning: "the tasks each party agrees to handle", meaningBn: "দায়িত্ব" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "We'd like to move forward. What exactly do you need from us?" },
      { speaker: "freelancer", text: "I'll need admin access to your Google Ads account so I can build and manage the campaigns." },
      { speaker: "client", text: "Okay, and what do we pay?" },
      { speaker: "freelancer", text: "My management fee is $400 per month, separate from whatever you spend directly with Google on ads." },
      { speaker: "client", text: "How will we know how it's going?" },
      { speaker: "freelancer", text: "You'll get a monthly report with the key numbers, plus a short call to review results together." },
    ],
    completionGuidance:
      "Objectives are met when access, responsibilities, fee structure, and reporting are all explained clearly and separately.",
  },
  {
    id: "TRACK-01",
    version: 1,
    category: "tracking",
    categoryLabel: CATEGORY_LABELS.tracking,
    title: "Explaining conversion tracking",
    situation: "Client does not understand conversion tracking.",
    learnerGoal: "Explain a conversion using the client's business example.",
    difficultyDefault: "beginner",
    estimatedMinutes: 7,
    brief:
      "Explain what a 'conversion' means using the client's own restaurant reservation example.",
    persona: {
      name: "Nadia Islam",
      role: "Owner",
      business: "Spice Table Restaurant",
      traits: ["nontechnical", "curious"],
    },
    facts: {
      business: "Restaurant accepting online table reservations",
    },
    openingMessage: "Everyone keeps saying 'conversions'. What does that actually mean for my restaurant?",
    objectives: [
      "Define conversion in plain language",
      "Use the client's own business example (reservations)",
      "Avoid unnecessary technical jargon",
      "Check that the client understood the explanation",
    ],
    vocabulary: [
      { phrase: "conversion", meaning: "a completed action that matters to the business, like a booking", meaningBn: "কনভার্সন" },
      { phrase: "reservation", meaning: "a booked table or appointment", meaningBn: "রিজার্ভেশন" },
      { phrase: "goal", meaning: "the specific action tracked as a success", meaningBn: "লক্ষ্য" },
      { phrase: "in plain terms", meaning: "explained simply, without jargon", meaningBn: "সহজ ভাষায়" },
      { phrase: "tracking", meaning: "recording user actions for measurement", meaningBn: "ট্র্যাকিং" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Everyone keeps saying 'conversions'. What does that mean for my restaurant?" },
      { speaker: "freelancer", text: "A conversion is simply an action that matters to your business, like someone completing an online table reservation." },
      { speaker: "client", text: "So if someone just visits the page, that's not a conversion?" },
      { speaker: "freelancer", text: "Right, just visiting isn't counted. It only counts once they finish the reservation form." },
      { speaker: "client", text: "That makes sense now." },
      { speaker: "freelancer", text: "Great — we'll track exactly that action so we know how many real bookings the ads bring in." },
    ],
    completionGuidance:
      "Objectives are met when the learner defines a conversion using the reservation example and confirms understanding.",
  },
  {
    id: "TRACK-02",
    version: 1,
    category: "tracking",
    categoryLabel: CATEGORY_LABELS.tracking,
    title: "Requesting access for tracking setup",
    situation: "Tracking setup needs access.",
    learnerGoal: "Request appropriate access to the website, tag manager, and analytics.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief: "You need specific access to set up tracking correctly. The client is hesitant to share account access.",
    persona: {
      name: "Omar Faruk",
      role: "Owner",
      business: "Faruk Auto Parts",
      traits: ["skeptical", "protective of his accounts"],
    },
    facts: {
      currentSetup: "No tag manager or analytics installed yet",
    },
    openingMessage: "Why do you need access to my website? Can't you just run the ads?",
    objectives: [
      "Explain why website/tag manager access is needed",
      "Name the specific access types required",
      "Offer alternatives such as inviting a developer instead",
      "Reassure about account security appropriately",
    ],
    vocabulary: [
      { phrase: "tag manager", meaning: "a tool to manage tracking codes on a website", meaningBn: "ট্যাগ ম্যানেজার" },
      { phrase: "analytics", meaning: "software that measures website visitor behavior", meaningBn: "অ্যানালিটিক্স" },
      { phrase: "admin access", meaning: "the highest level of account permission", meaningBn: "অ্যাডমিন অ্যাক্সেস" },
      { phrase: "editor access", meaning: "permission to make changes, but not full control", meaningBn: "এডিটর অ্যাক্সেস" },
      { phrase: "developer", meaning: "the person who built or maintains the website code", meaningBn: "ডেভেলপার" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Why do you need access to my website? Can't you just run the ads?" },
      { speaker: "freelancer", text: "I need to check that important actions, like purchases or enquiries, are measured correctly." },
      { speaker: "client", text: "What exactly do you need access to?" },
      { speaker: "freelancer", text: "Editor access to Google Tag Manager and Analytics would be enough, I don't need your hosting login." },
      { speaker: "client", text: "And if I'd rather not share that?" },
      { speaker: "freelancer", text: "Your developer can install it instead, I can send them clear setup instructions." },
    ],
    completionGuidance:
      "Objectives are met when the learner names specific access types and offers a respectful alternative.",
  },
  {
    id: "TRACK-03",
    version: 1,
    category: "tracking",
    categoryLabel: CATEGORY_LABELS.tracking,
    title: "Numbers don't match",
    situation: "Analytics and ad platform totals disagree.",
    learnerGoal: "Explain possible measurement differences without inventing a diagnosis.",
    difficultyDefault: "advanced",
    estimatedMinutes: 8,
    brief:
      "The client noticed that Google Ads reports 40 leads this month but Analytics shows 30. Explain honestly without guessing at a cause you haven't verified.",
    persona: {
      name: "Farida Rahman",
      role: "Marketing Coordinator",
      business: "Rahman Interiors",
      traits: ["detail-oriented", "skeptical"],
    },
    facts: {
      googleAdsLeads: "40 leads reported this month",
      analyticsLeads: "30 leads reported this month",
    },
    openingMessage: "Google Ads says we got 40 leads, but Analytics only shows 30. Which one is correct?",
    objectives: [
      "Explain that different tools can measure and attribute differently",
      "Avoid inventing a specific cause without checking",
      "Propose a way to investigate the discrepancy",
      "Keep the client's trust with transparent language",
    ],
    vocabulary: [
      { phrase: "discrepancy", meaning: "a difference between two numbers that should match", meaningBn: "গরমিল" },
      { phrase: "attribution", meaning: "assigning credit for a conversion to a source", meaningBn: "অ্যাট্রিবিউশন" },
      { phrase: "double counting", meaning: "counting the same action more than once", meaningBn: "দ্বিগুণ গণনা" },
      { phrase: "measurement window", meaning: "the time period counted by a report", meaningBn: "পরিমাপের সময়কাল" },
      { phrase: "data discrepancy investigation", meaning: "a structured check into why numbers differ", meaningBn: "তথ্য গরমিল অনুসন্ধান" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Google Ads says we got 40 leads, but Analytics only shows 30. Which one is correct?" },
      { speaker: "freelancer", text: "Both tools can be partly right, they often count and attribute conversions differently." },
      { speaker: "client", text: "So what caused the difference this time?" },
      { speaker: "freelancer", text: "I don't want to guess without checking the setup first, let's investigate together." },
      { speaker: "client", text: "What would you check?" },
      { speaker: "freelancer", text: "I'll compare the tracked events and time windows in both tools and report back with what I actually find." },
    ],
    completionGuidance:
      "Objectives are met when the learner avoids fabricating a cause and proposes a genuine investigation step.",
  },
  {
    id: "TRACK-04",
    version: 1,
    category: "tracking",
    categoryLabel: CATEGORY_LABELS.tracking,
    title: "Duplicated events",
    situation: "Purchase or form events appear duplicated.",
    learnerGoal: "Explain testing, verification, and what remains unknown.",
    difficultyDefault: "advanced",
    estimatedMinutes: 8,
    brief:
      "The client believes their purchase count looks doubled. Investigate calmly and communicate honestly about what is confirmed and what needs testing.",
    persona: {
      name: "Zahid Karim",
      role: "Owner",
      business: "Karim Electronics Online",
      traits: ["worried about wasted ad spend", "detail-oriented"],
    },
    facts: {
      reportedPurchases: "Dashboard shows 120 purchases, but only ~60 orders exist in the store",
    },
    openingMessage: "Our dashboard shows 120 purchases this week, but our store only had about 60 orders. What's going on?",
    objectives: [
      "Acknowledge the concern seriously",
      "Explain that this may be a tracking issue, such as duplicate firing",
      "Propose a specific test to confirm the cause",
      "Avoid claiming certainty before testing",
    ],
    vocabulary: [
      { phrase: "duplicate event", meaning: "the same action recorded more than once", meaningBn: "ডুপ্লিকেট ইভেন্ট" },
      { phrase: "firing twice", meaning: "a tracking tag activating more than intended", meaningBn: "দুইবার ট্রিগার হওয়া" },
      { phrase: "confirmation page", meaning: "the page shown after a completed purchase", meaningBn: "নিশ্চিতকরণ পেজ" },
      { phrase: "test purchase", meaning: "a sample transaction used to verify tracking", meaningBn: "পরীক্ষামূলক ক্রয়" },
      { phrase: "root cause", meaning: "the underlying reason for a problem", meaningBn: "মূল কারণ" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Our dashboard shows 120 purchases this week, but our store only had about 60 orders." },
      { speaker: "freelancer", text: "That's a real concern, and it looks like the purchase event may be firing more than once per order." },
      { speaker: "client", text: "Are you sure that's the reason?" },
      { speaker: "freelancer", text: "Not yet, I want to run a test purchase and check if the confirmation page triggers the event twice." },
      { speaker: "client", text: "Okay, please let me know what you find." },
      { speaker: "freelancer", text: "I will, and I won't change any ad budgets based on this number until we confirm the real count." },
    ],
    completionGuidance:
      "Objectives are met when the learner proposes a verification test and avoids overstating certainty.",
  },
  {
    id: "META-01",
    version: 1,
    category: "meta-ads",
    categoryLabel: CATEGORY_LABELS["meta-ads"],
    title: "New campaign needs creative assets",
    situation: "New campaign needs creative assets.",
    learnerGoal: "Ask about the offer, audience, images, and approval process.",
    difficultyDefault: "beginner",
    estimatedMinutes: 7,
    brief: "Plan a new Meta Ads campaign for a client who hasn't prepared any creative assets yet.",
    persona: {
      name: "Priya Sen",
      role: "Owner",
      business: "Sen Jewellery Boutique",
      traits: ["friendly", "visual-minded", "new to Meta Ads"],
    },
    facts: {
      product: "Handmade jewellery",
      currentAssets: "A few phone photos, no professional images yet",
    },
    openingMessage: "I'm ready to start Meta ads for my jewellery. What do you need from me?",
    objectives: [
      "Ask about the specific offer or product being promoted",
      "Ask about the target audience",
      "Ask what images or videos are currently available",
      "Explain the creative approval process",
    ],
    vocabulary: [
      { phrase: "creative assets", meaning: "images and videos used in ads", meaningBn: "ক্রিয়েটিভ অ্যাসেট" },
      { phrase: "ad copy", meaning: "the written text in an advertisement", meaningBn: "বিজ্ঞাপনের লেখা" },
      { phrase: "approval process", meaning: "the steps to review and confirm ad content", meaningBn: "অনুমোদন প্রক্রিয়া" },
      { phrase: "audience targeting", meaning: "choosing who sees an ad", meaningBn: "অডিয়েন্স টার্গেটিং" },
      { phrase: "product photography", meaning: "professional images of products", meaningBn: "পণ্যের আলোকচিত্র" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "I'm ready to start Meta ads for my jewellery. What do you need from me?" },
      { speaker: "freelancer", text: "Let's start with the offer, which pieces or collection do you want to promote first?" },
      { speaker: "client", text: "Probably my new necklace collection." },
      { speaker: "freelancer", text: "Great. Do you have professional photos, or just phone pictures for now?" },
      { speaker: "client", text: "Just phone photos right now." },
      { speaker: "freelancer", text: "That's a fine starting point. I'll also ask you to approve the ad text and images before anything goes live." },
    ],
    completionGuidance:
      "Objectives are met when offer, audience, available assets, and approval process are all covered.",
  },
  {
    id: "META-02",
    version: 1,
    category: "meta-ads",
    categoryLabel: CATEGORY_LABELS["meta-ads"],
    title: "Too many low-quality leads",
    situation: "Client receives many low-quality leads.",
    learnerGoal: "Discuss lead quality and propose a measured test.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief: "The client is frustrated that most leads from Meta Ads are not serious buyers.",
    persona: {
      name: "Rafiq Uddin",
      role: "Sales Manager",
      business: "Uddin Real Estate",
      traits: ["frustrated", "results-focused"],
    },
    facts: {
      leadVolume: "150 leads last month",
      qualifiedRate: "Only about 10% seem genuinely interested",
    },
    openingMessage: "We're getting tons of leads, but almost none of them are serious buyers. What's happening?",
    objectives: [
      "Acknowledge the frustration",
      "Ask clarifying questions about how leads are qualified",
      "Explain possible reasons like broad targeting or unclear ad copy",
      "Propose a specific, measured test to improve quality",
    ],
    vocabulary: [
      { phrase: "qualified lead", meaning: "a lead likely to become a real customer", meaningBn: "উপযুক্ত লিড" },
      { phrase: "lead volume", meaning: "the total number of leads generated", meaningBn: "লিড সংখ্যা" },
      { phrase: "broad targeting", meaning: "showing ads to a wide, less specific audience", meaningBn: "বিস্তৃত টার্গেটিং" },
      { phrase: "filter question", meaning: "a form question that screens serious leads", meaningBn: "যাচাই প্রশ্ন" },
      { phrase: "measured test", meaning: "a small controlled change to observe results", meaningBn: "পরিমাপযোগ্য পরীক্ষা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "We're getting tons of leads, but almost none are serious buyers. What's happening?" },
      { speaker: "freelancer", text: "I understand the frustration, wasted time on unqualified leads is costly." },
      { speaker: "client", text: "Can you fix the targeting?" },
      { speaker: "freelancer", text: "Possibly, it could also be the ad copy attracting the wrong people. Can you tell me how you're currently judging quality?" },
      { speaker: "client", text: "Mostly by whether they respond to our follow-up calls." },
      { speaker: "freelancer", text: "Let's add a qualifying question to the lead form and test narrower targeting for two weeks, then compare results." },
    ],
    completionGuidance:
      "Objectives are met when the learner discusses possible causes and proposes a specific measured test.",
  },
  {
    id: "META-03",
    version: 1,
    category: "meta-ads",
    categoryLabel: CATEGORY_LABELS["meta-ads"],
    title: "Performance drops after repeated creative use",
    situation: "Performance falls after repeated creative use.",
    learnerGoal: "Explain a creative refresh and agree on next steps.",
    difficultyDefault: "advanced",
    estimatedMinutes: 8,
    brief: "The same ad creative has been running for two months and results are declining.",
    persona: {
      name: "Meherun Nesa",
      role: "Owner",
      business: "Nesa Skincare",
      traits: ["detail-oriented", "worried about spending more for less"],
    },
    facts: {
      creativeAge: "Same ad images used for 2 months",
      performanceTrend: "Click-through rate has dropped by half",
    },
    openingMessage: "Our results have been getting worse the last few weeks. Did something break?",
    objectives: [
      "Explain the concept of ad fatigue in plain terms",
      "Connect the decline to the creative running for a long time",
      "Propose a creative refresh plan",
      "Agree on a timeline to review results after the change",
    ],
    vocabulary: [
      { phrase: "ad fatigue", meaning: "declining performance from an audience seeing the same ad too often", meaningBn: "বিজ্ঞাপন ক্লান্তি" },
      { phrase: "click-through rate", meaning: "the percentage of viewers who click an ad", meaningBn: "ক্লিক-থ্রু রেট" },
      { phrase: "creative refresh", meaning: "replacing ad images or videos with new ones", meaningBn: "ক্রিয়েটিভ রিফ্রেশ" },
      { phrase: "frequency", meaning: "how often the same person sees an ad", meaningBn: "ফ্রিকোয়েন্সি" },
      { phrase: "performance trend", meaning: "the direction results are moving over time", meaningBn: "পারফরম্যান্স প্রবণতা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Our results have been getting worse the last few weeks. Did something break?" },
      { speaker: "freelancer", text: "Nothing is broken, but the same ad images have been running for two months, which often causes fatigue." },
      { speaker: "client", text: "So people are just tired of seeing it?" },
      { speaker: "freelancer", text: "Exactly, the audience has likely seen it many times, so its effectiveness naturally drops." },
      { speaker: "client", text: "What should we do?" },
      { speaker: "freelancer", text: "Let's prepare a few new creative variations and review performance again after two weeks." },
    ],
    completionGuidance:
      "Objectives are met when the learner explains ad fatigue plainly and proposes a refresh plan with a review point.",
  },
  {
    id: "TIKTOK-01",
    version: 1,
    category: "tiktok-ads",
    categoryLabel: CATEGORY_LABELS["tiktok-ads"],
    title: "No suitable video assets",
    situation: "Client has no suitable video assets.",
    learnerGoal: "Explain the creative brief and request usable material.",
    difficultyDefault: "beginner",
    estimatedMinutes: 7,
    brief: "The client wants to run TikTok ads but only has static product photos, no video.",
    persona: {
      name: "Tania Rahman",
      role: "Founder",
      business: "GlowUp Cosmetics",
      traits: ["enthusiastic", "new to short-form video"],
    },
    facts: {
      currentAssets: "Only product photos, no video footage",
      platform: "TikTok, which favors native short video",
    },
    openingMessage: "I only have product photos. Can we still run TikTok ads with those?",
    objectives: [
      "Explain that TikTok favors native short video style",
      "Describe what a simple creative brief needs",
      "Request specific, achievable video material",
      "Offer practical options if professional video isn't available",
    ],
    vocabulary: [
      { phrase: "native style", meaning: "content that looks natural to the platform, not overly polished", meaningBn: "স্বাভাবিক ধাঁচের কনটেন্ট" },
      { phrase: "creative brief", meaning: "a short document describing what content is needed", meaningBn: "ক্রিয়েটিভ ব্রিফ" },
      { phrase: "short-form video", meaning: "brief video content, usually under a minute", meaningBn: "শর্ট-ফর্ম ভিডিও" },
      { phrase: "user-generated content", meaning: "content made by everyday users, not professionals", meaningBn: "ব্যবহারকারী-নির্মিত কনটেন্ট" },
      { phrase: "hook", meaning: "the first few seconds designed to grab attention", meaningBn: "আকর্ষণ তৈরি করার অংশ" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "I only have product photos. Can we still run TikTok ads with those?" },
      { speaker: "freelancer", text: "Photos can work as a backup, but TikTok performs much better with short, native-style video." },
      { speaker: "client", text: "I don't have a video team though." },
      { speaker: "freelancer", text: "That's fine, even a simple phone video showing the product being used can work well." },
      { speaker: "client", text: "What exactly should I film?" },
      { speaker: "freelancer", text: "I'll send a short creative brief with a few easy shot ideas and a strong opening hook." },
    ],
    completionGuidance:
      "Objectives are met when the learner explains the video preference and requests specific, realistic material.",
  },
  {
    id: "TIKTOK-02",
    version: 1,
    category: "tiktok-ads",
    categoryLabel: CATEGORY_LABELS["tiktok-ads"],
    title: "Expecting immediate results",
    situation: "Client expects immediate results.",
    learnerGoal: "Explain test objectives and agree on a review point.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 7,
    brief: "The campaign launched yesterday and the client is already asking about sales.",
    persona: {
      name: "Sabbir Hossain",
      role: "Owner",
      business: "Hossain Sneaker Store",
      traits: ["impatient", "excited about the new channel"],
    },
    facts: {
      campaignAge: "Launched 1 day ago",
      testingPlan: "Planned as a 2-week initial test",
    },
    openingMessage: "The ads went live yesterday. How many sales do we have so far?",
    objectives: [
      "Explain that platforms usually need time to optimize",
      "Set a realistic timeline for meaningful results",
      "Restate the test objective clearly",
      "Agree on a specific date to review performance",
    ],
    vocabulary: [
      { phrase: "learning phase", meaning: "the initial period when an ad platform optimizes delivery", meaningBn: "লার্নিং ফেজ" },
      { phrase: "initial test", meaning: "a first small-scale trial of a campaign", meaningBn: "প্রাথমিক পরীক্ষা" },
      { phrase: "review point", meaning: "an agreed date to evaluate results", meaningBn: "পর্যালোচনার তারিখ" },
      { phrase: "early data", meaning: "results collected soon after launch, often unstable", meaningBn: "প্রাথমিক তথ্য" },
      { phrase: "patience window", meaning: "the time needed before judging a campaign fairly", meaningBn: "ধৈর্যের সময়কাল" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "The ads went live yesterday. How many sales do we have so far?" },
      { speaker: "freelancer", text: "It's very early, the platform is still in its learning phase and results can be unstable at this stage." },
      { speaker: "client", text: "So when will we know if it's working?" },
      { speaker: "freelancer", text: "We planned this as a two-week test, so let's review the real numbers together at the end of that period." },
      { speaker: "client", text: "Okay, that makes sense." },
      { speaker: "freelancer", text: "I'll still keep an eye on it daily and flag anything unusual before then." },
    ],
    completionGuidance:
      "Objectives are met when the learner explains the learning phase and secures agreement on a specific review date.",
  },
  {
    id: "TIKTOK-03",
    version: 1,
    category: "tiktok-ads",
    categoryLabel: CATEGORY_LABELS["tiktok-ads"],
    title: "Does the audience fit?",
    situation: "Client questions whether the audience fits.",
    learnerGoal: "Ask about customers and discuss how to evaluate fit.",
    difficultyDefault: "advanced",
    estimatedMinutes: 8,
    brief: "The client worries TikTok's younger audience doesn't match their more mature customer base.",
    persona: {
      name: "Abdul Kader",
      role: "Owner",
      business: "Kader Home Furniture",
      traits: ["thoughtful", "cautious about new platforms"],
    },
    facts: {
      typicalCustomer: "Homeowners aged 35-55",
      platformPerception: "Client believes TikTok is only for teenagers",
    },
    openingMessage: "Isn't TikTok mostly for teenagers? I'm not sure my furniture customers are even there.",
    objectives: [
      "Ask about the client's actual customer profile",
      "Correct the misconception with balanced, honest information",
      "Discuss how audience fit can be evaluated with a small test",
      "Avoid overpromising that TikTok will definitely work",
    ],
    vocabulary: [
      { phrase: "audience fit", meaning: "how well a platform's users match your target customers", meaningBn: "অডিয়েন্স উপযোগিতা" },
      { phrase: "demographic", meaning: "a section of a population defined by age, gender, etc.", meaningBn: "ডেমোগ্রাফিক" },
      { phrase: "misconception", meaning: "a belief that is not accurate", meaningBn: "ভুল ধারণা" },
      { phrase: "pilot campaign", meaning: "a small trial campaign to test viability", meaningBn: "পাইলট ক্যাম্পেইন" },
      { phrase: "customer profile", meaning: "a description of a business's typical customer", meaningBn: "গ্রাহক প্রোফাইল" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Isn't TikTok mostly for teenagers? I'm not sure my furniture customers are even there." },
      { speaker: "freelancer", text: "That's a common idea, but TikTok's audience has grown to include many adults now too. Who is your typical customer?" },
      { speaker: "client", text: "Mostly homeowners between 35 and 55." },
      { speaker: "freelancer", text: "That age group is present on TikTok, though maybe a smaller share than younger users." },
      { speaker: "client", text: "Is it worth trying then?" },
      { speaker: "freelancer", text: "I'd suggest a small pilot campaign to see how that audience responds before committing a larger budget." },
    ],
    completionGuidance:
      "Objectives are met when the learner corrects the misconception honestly and proposes a measured way to test fit.",
  },
  {
    id: "REPORT-01",
    version: 1,
    category: "reporting",
    categoryLabel: CATEGORY_LABELS.reporting,
    title: "Presenting a successful month",
    situation: "Present a successful monthly report.",
    learnerGoal: "Summarize results, limitations, and next actions.",
    difficultyDefault: "beginner",
    estimatedMinutes: 7,
    brief: "Spend was $1,000, generating 500 clicks and 20 leads (CPC $2, CPL $50). Present this clearly.",
    persona: {
      name: "Joya Akter",
      role: "Owner",
      business: "Akter Beauty Salon",
      traits: ["friendly", "appreciates clear numbers"],
    },
    facts: {
      spend: "$1,000",
      clicks: "500",
      leads: "20",
      cpc: "$2.00",
      cpl: "$50.00",
    },
    openingMessage: "Hi! How did the campaign do this month?",
    objectives: [
      "Summarize spend, clicks, and leads clearly",
      "State the CPC and CPL correctly based on the numbers",
      "Mention a limitation or open question honestly",
      "Suggest a specific next action",
    ],
    vocabulary: [
      { phrase: "cost per click (CPC)", meaning: "total spend divided by clicks", meaningBn: "প্রতি ক্লিকের খরচ" },
      { phrase: "cost per lead (CPL)", meaning: "total spend divided by leads", meaningBn: "প্রতি লিডের খরচ" },
      { phrase: "monthly report", meaning: "a summary of performance over a month", meaningBn: "মাসিক প্রতিবেদন" },
      { phrase: "next action", meaning: "the recommended step going forward", meaningBn: "পরবর্তী পদক্ষেপ" },
      { phrase: "limitation", meaning: "a constraint or gap in the current data", meaningBn: "সীমাবদ্ধতা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "Hi! How did the campaign do this month?" },
      { speaker: "freelancer", text: "Good news, we spent $1,000 and got 500 clicks and 20 leads, so cost per lead was $50." },
      { speaker: "client", text: "Is $50 per lead good?" },
      { speaker: "freelancer", text: "It's a reasonable start, though we don't yet know how many of these leads became paying customers." },
      { speaker: "client", text: "What should we do next?" },
      { speaker: "freelancer", text: "Let's track which leads convert to sales next month so we can judge true value, not just lead cost." },
    ],
    completionGuidance:
      "Objectives are met when spend, CPC, CPL, a limitation, and a next action are all mentioned accurately.",
  },
  {
    id: "REPORT-02",
    version: 1,
    category: "reporting",
    categoryLabel: CATEGORY_LABELS.reporting,
    title: "Missing the target",
    situation: "Campaign misses the agreed target.",
    learnerGoal: "Acknowledge the result and explain a specific improvement plan.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 8,
    brief: "The agreed target was 30 leads this month, but only 18 were generated.",
    persona: {
      name: "Rezaul Karim",
      role: "Owner",
      business: "Karim Fitness Studio",
      traits: ["disappointed but reasonable"],
    },
    facts: {
      target: "30 leads",
      actual: "18 leads",
      spend: "$900",
    },
    openingMessage: "We agreed on 30 leads, but I only see 18 this month. What happened?",
    objectives: [
      "Acknowledge the missed target honestly",
      "Avoid making excuses without a real explanation",
      "Explain a specific, credible reason if known",
      "Propose a concrete improvement plan for next month",
    ],
    vocabulary: [
      { phrase: "agreed target", meaning: "the goal both parties committed to", meaningBn: "সম্মত লক্ষ্যমাত্রা" },
      { phrase: "shortfall", meaning: "the amount by which a result falls short of a goal", meaningBn: "ঘাটতি" },
      { phrase: "improvement plan", meaning: "a specific set of actions to raise performance", meaningBn: "উন্নয়ন পরিকল্পনা" },
      { phrase: "accountability", meaning: "taking responsibility for results", meaningBn: "জবাবদিহিতা" },
      { phrase: "root issue", meaning: "the main underlying cause of a problem", meaningBn: "মূল সমস্যা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "We agreed on 30 leads, but I only see 18 this month. What happened?" },
      { speaker: "freelancer", text: "You're right, we fell short of the target, and I want to explain why and what we'll change." },
      { speaker: "client", text: "Please go ahead." },
      { speaker: "freelancer", text: "Two of our best-performing ads were paused by the platform for review, which limited reach for a week." },
      { speaker: "client", text: "What will you do differently?" },
      { speaker: "freelancer", text: "I'll prepare backup ad variations in advance so a single pause doesn't affect the whole campaign again." },
    ],
    completionGuidance:
      "Objectives are met when the learner acknowledges the shortfall honestly and proposes a specific improvement plan.",
  },
  {
    id: "REPORT-03",
    version: 1,
    category: "reporting",
    categoryLabel: CATEGORY_LABELS.reporting,
    title: "Explaining CPC, CPL, CPA, and ROAS",
    situation: "Client asks about CPC, CPL, CPA, and ROAS.",
    learnerGoal: "Explain the relevant metric simply using supplied numbers.",
    difficultyDefault: "intermediate",
    estimatedMinutes: 8,
    brief: "The client is confused by advertising acronyms and wants simple explanations using their own numbers.",
    persona: {
      name: "Mahin Chowdhury",
      role: "Owner",
      business: "Chowdhury Travel Agency",
      traits: ["curious", "wants to learn the basics"],
    },
    facts: {
      spend: "$800",
      clicks: "400",
      leads: "16",
      customers: "4",
      revenue: "$1,600",
    },
    openingMessage: "I keep seeing CPC, CPL, CPA, ROAS in your reports. Can you explain what these mean for my numbers?",
    objectives: [
      "Explain CPC, CPL, CPA, and ROAS in plain language",
      "Calculate each metric correctly from the supplied numbers",
      "Only calculate ROAS because revenue was actually provided",
      "Check the client's understanding before moving on",
    ],
    vocabulary: [
      { phrase: "CPC (cost per click)", meaning: "spend divided by clicks", meaningBn: "প্রতি ক্লিকের খরচ" },
      { phrase: "CPL (cost per lead)", meaning: "spend divided by leads", meaningBn: "প্রতি লিডের খরচ" },
      { phrase: "CPA (cost per acquisition)", meaning: "spend divided by paying customers gained", meaningBn: "প্রতি গ্রাহক অর্জনের খরচ" },
      { phrase: "ROAS (return on ad spend)", meaning: "revenue divided by ad spend", meaningBn: "বিজ্ঞাপন খরচের প্রতিদান" },
      { phrase: "attributable revenue", meaning: "revenue that can be reasonably credited to the campaign", meaningBn: "সম্পর্কিত রাজস্ব" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "I keep seeing CPC, CPL, CPA, ROAS. Can you explain what these mean for my numbers?" },
      { speaker: "freelancer", text: "Sure. Your CPC is spend divided by clicks: $800 over 400 clicks is $2 per click." },
      { speaker: "client", text: "And the lead cost?" },
      { speaker: "freelancer", text: "CPL is spend divided by leads: $800 over 16 leads is $50 per lead." },
      { speaker: "client", text: "What about CPA and ROAS?" },
      { speaker: "freelancer", text: "CPA is spend per paying customer, $800 over 4 customers is $200. Since you had $1,600 revenue, ROAS is 2, meaning $2 back for every $1 spent." },
    ],
    completionGuidance:
      "Objectives are met when each metric is calculated correctly and only from the numbers actually supplied.",
  },
  {
    id: "REPORT-04",
    version: 1,
    category: "reporting",
    categoryLabel: CATEGORY_LABELS.reporting,
    title: "Where to allocate next month's budget",
    situation: "Client asks where to allocate next month's budget.",
    learnerGoal: "Explain a recommendation with evidence and uncertainty.",
    difficultyDefault: "advanced",
    estimatedMinutes: 8,
    brief: "The client has $1,200 for next month and wants a recommendation across two channels based on this month's data.",
    persona: {
      name: "Sultana Begum",
      role: "Owner",
      business: "Begum Boutique",
      traits: ["decisive", "wants clear reasoning"],
    },
    facts: {
      googleAdsCpl: "$40 cost per lead this month",
      metaCpl: "$65 cost per lead this month",
      totalBudget: "$1,200 for next month",
    },
    openingMessage: "We have $1,200 for next month. Should we put it all into Google Ads since it's cheaper?",
    objectives: [
      "Reference the actual CPL numbers for each channel",
      "Explain the reasoning behind a recommendation",
      "Acknowledge uncertainty rather than overstating confidence",
      "Suggest keeping some budget diversified if reasonable",
    ],
    vocabulary: [
      { phrase: "budget allocation", meaning: "how spending is divided across channels", meaningBn: "বাজেট বরাদ্দ" },
      { phrase: "channel", meaning: "a platform used for advertising, like Google or Meta", meaningBn: "চ্যানেল" },
      { phrase: "diversify", meaning: "spread budget or risk across multiple options", meaningBn: "বৈচিত্র্যকরণ" },
      { phrase: "data-driven recommendation", meaning: "a suggestion based on measured evidence", meaningBn: "তথ্যভিত্তিক সুপারিশ" },
      { phrase: "uncertainty", meaning: "acknowledging that outcomes are not guaranteed", meaningBn: "অনিশ্চয়তা" },
    ],
    sampleDialogue: [
      { speaker: "client", text: "We have $1,200 for next month. Should we put it all into Google Ads since it's cheaper?" },
      { speaker: "freelancer", text: "Google Ads had a lower cost per lead this month, $40 versus $65 on Meta." },
      { speaker: "client", text: "So all-in on Google then?" },
      { speaker: "freelancer", text: "I'd lean that way, but one month of data isn't fully conclusive, so I'd keep a smaller test budget on Meta too." },
      { speaker: "client", text: "How would you split it?" },
      { speaker: "freelancer", text: "Maybe $900 to Google Ads and $300 to Meta, then we reassess with more data next month." },
    ],
    completionGuidance:
      "Objectives are met when the learner cites the actual numbers, explains reasoning, and avoids overstating certainty.",
  },
];

// Append additions so existing IDs and ordering remain stable for saved sessions.
SCENARIOS.push(...ADDITIONAL_SCENARIOS);

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((scenario) => scenario.id === id);
}

export const SCENARIO_CATEGORIES: { id: Scenario["category"]; label: string }[] = [
  { id: "website", label: CATEGORY_LABELS.website },
  { id: "google-ads", label: CATEGORY_LABELS["google-ads"] },
  { id: "tracking", label: CATEGORY_LABELS.tracking },
  { id: "meta-ads", label: CATEGORY_LABELS["meta-ads"] },
  { id: "tiktok-ads", label: CATEGORY_LABELS["tiktok-ads"] },
  { id: "reporting", label: CATEGORY_LABELS.reporting },
  ...PRACTICE_THEMES.map((theme) => ({ id: theme.id, label: theme.categoryLabel })),
];
